apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-deployment-perfect
  labels:
    app: nginx-app-deployment-perfect
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app-deployment-perfect
  template:
    metadata:
      labels:
        app: nginx-app-deployment-perfect
    spec:
      containers:
      - name: nginx-app
        image: nginx
        ports:
        - containerPort: 80
