apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-pod
spec:
  initContainers:
  - name: init-yunjinservice
    image: nginx
    command: ['sh', '-c', 'sleep 2; echo helloworld01;']
  - name: init-yunjindb  
    image: nginx
    command: ['sh', '-c', 'sleep 2; echo yunjindb;']
  containers:
  - name: yunjin-pod
    image: nginx
    command: ['sh', '-c', 'sleep 2; echo fun fun cicd! && sleep 36000;']
    resources:
      requests:
        cpu: 0.2
        memory: 0.2
      limits:
        cpu: 0.5
        memory: 1
    ports:
    - containerPort: 8080
    env:
    - name: yunjin_env # 파드가 실행되는 호스트 네임을 파드 안에서 확인하는 설정
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName # 현재 노드를 뜻함