apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-pod
spec:
  initContainers:
  - name: init-jiwanservice
    image: nginx
    command: ["sh", "-c", "sleep 2", "echo init jiwanservice"]
  - name: init-jiwandb
    image: nginx
    command: ["sh", "-c", "sleep 2", "echo init jiwandb"]
  containers:
  - name: jiwan-pod
    image: nginx
    command: ["sh", "-c", "echo fun cicd! && sleep 36000"]
    resources:
      requests:
        cpu: "200m"
        memory: "200M"
      limits:
        cpu: "500m"
        memory: "1G"
    ports:
    - containerPort: 8080
    env:
      - name: JIWAN_ENV
        value: jiwan_env
